require("dotenv").config();

const {
  ACCESS_TOKEN_SECRETE,
  ACCESS_TOKEN_EXPIRES_IN,
  REFRESH_TOKEN_SECRET,
  REFRESH_TOKEN_EXPIRES_IN,
  PORT,
  DB_URL,
} = process.env;
const CONSTANTS = {
  PORT: PORT || 5000,
  DB_URL: DB_URL || "mongodb://127.0.0.1:27017/chat-new-DB",
  ACCESS_TOKEN_SECRETE,
  ACCESS_TOKEN_EXPIRES_IN,
  REFRESH_TOKEN_SECRET,
  REFRESH_TOKEN_EXPIRES_IN,
};

module.exports = CONSTANTS;
